import type { Metadata } from "next";
import { Mulish, Oswald } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  variable: "--font-inter", // Keep variable name same so globals.css works
  subsets: ["latin", "vietnamese"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import GlobalHeader from "@/components/GlobalHeader";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mulish.variable} ${oswald.variable} h-full antialiased font-sans`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalHeader />
        {children}
      </body>
    </html>
  );
}
